### ISSUE TITLE
No such file or directory: 'icon_play'

### ISSUE THREAD

**Issue by joaobibiano** [EnriqueMoran/lumberjackBot#2]
Hi, i'm receiving this message 

Traceback (most recent call last):
  File "C:\Users\jvbib\Desktop\lumberjackBot-master\lumberjackBot.py", line 66, in <module>
    playX, playY = pyautogui.locateCenterOnScreen('icon_play')
  File "C:\Users\jvbib\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pyscreeze-0.1.14-py3.6.egg\pyscreeze\__init__.py", line 295, in locateCenterOnScreen
    coords = locateOnScreen(image, **kwargs)
  File "C:\Users\jvbib\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pyscreeze-0.1.14-py3.6.egg\pyscreeze\__init__.py", line 266, in locateOnScreen
    retVal = locate(image, screenshotIm, **kwargs)
  File "C:\Users\jvbib\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pyscreeze-0.1.14-py3.6.egg\pyscreeze\__init__.py", line 250, in locate
    points = tuple(locateAll(needleImage, haystackImage, **kwargs))
  File "C:\Users\jvbib\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pyscreeze-0.1.14-py3.6.egg\pyscreeze\__init__.py", line 165, in _locateAll_python
    needleFileObj = open(needleImage, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'icon_play'

But in elements html, the names the same at python.

Some idea? I'm doing some wrong?

**Comment by joaobibiano** [comment]
Sorry, I got use.
